command: [
  "python", 
  "app.py"
]

env:
  - name: "SERVING_ENDPOINT"
    valueFrom: "serving-endpoint"

resources:
  serving-endpoint:
    type: "serving-endpoint"
    name: "databricks-claude-3-7-sonnet"
    permissions:
      - level: "CAN_QUERY"
